name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: false
        install: >-
          mingw-w64-x86_64-clang-tools-extra

    # - name: Compile project
    #   shell: msys2 {0}
    #   run: make CC=clang

    - name: Check format
      shell: msys2 {0}
      run: |
        make format
        if ! git diff --exit-code; then
          echo "::error title=Formatting Check Failed::Code is not formatted according to .clang-format. Please run 'make format' locally and commit the changes."
          exit 1
        fi

    - name: Check lint
      shell: msys2 {0}
      run: |
        if ! make tidy; then
          echo "::error title=Linting Check Failed::Code violates .clang-tidy rules. Please review the logs, fix the warnings, and test locally with 'make tidy'."
          exit 1
        fi
